#!/bin/sh
to_dir="src/main"
thrift_dir="$to_dir/thrift/"

for lang in cpp java python; do
    for thrift_file in `find $thrift_dir -name \*.thrift`; do
        thrift --gen $lang -o "$to_dir" "$thrift_file"
    done
done
