#!/bin/sh
to_dir="src/main"
thrift_dir="$to_dir/thrift/"

for lang in cpp java py; do
    doit=`find "$to_dir/gen-$lang" \! -cnewer src/main/thrift/\* 2>/dev/null || echo doit`
    if test -n "$doit"; then
        #src/main/thrift/hfc_db.thrift do;
        for thrift_file in `find $thrift_dir -name \*.thrift`; do
            thrift -v --gen $lang -o "$to_dir" "$thrift_file"
        done
    fi
done
