[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "hfc_thrift"
version = "0.0.1"
requires-python = ">=3.10"
dependencies = [
  "thrift >= 0.20.0",
]
